### ISSUE TITLE
Broid sdk not in npm registry ?

### ISSUE THREAD

**Issue by chrisribe** [broidHQ/broid-kit#24]
Seems that the sdk is not in the npm registry...
Unless this is just not ready (you are in beta so I understand).

`npm ERR! 404 Not found : @broid/api-js-sdk
npm ERR! 404
npm ERR! 404  '@broid/api-js-sdk' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)

npm ERR! Please include the following file with any support request:
npm ERR!     C:\cribe\Broid\npm-debug.log
`
I have attached the debug log.
[npm-debug.txt](https://github.com/broidHQ/broid-kit/files/1232016/npm-debug.txt)

Chris

**Comment by killix** [comment]
Hi Chris,

Weird because you can find broid-kit here https://www.npmjs.com/package/@broid/kit and the sdk here https://www.npmjs.com/package/@broid/api-sdk

Can you copy/paste the exact command you run to try to understand your issue?
